GENERAL_COMPONENT_PADDING_X = 5
GENERAL_COMPONENT_PADDING_Y = 5
COMPONENT_PADDING_X = 5
COMPONENT_PADDING_Y = 2
BUTTON_PADDING_X = 10
BUTTON_PADDING_Y = 5
LEFT_COLUMN_BG = 'lightgray'
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 800

FONT_1 = 18
FONT_2 = 16
FONT_3 = 14
FONT_4 = 12